powershell -command -(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/nazarpunk/cheapack/master/sdk/common.j.lua', 'common.j.lua')
powershell -command -(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/nazarpunk/cheapack/master/sdk/blizzard.j.lua', 'blizzard.j.lua')
powershell -command -(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/nazarpunk/cheapack/master/sdk/common.ai.j.lua', 'common.ai.j.lua')
powershell -command -(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/nazarpunk/cheapack/master/sdk/cheats.j.lua', 'cheats.j.lua')
powershell -command -(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/nazarpunk/cheapack/master/sdk/types.lua', 'types.lua')